<?php

class Wording {

    private static $wordingArray = array(
        //monster scene
        'lv' => array('Lv', 'Lv', '攻击值'),
        'exp' => array('Exp', 'Exp', '攻击值'),
        'hp' => array('HP', 'พลังชีวิต', '生命值'),
        'atk' => array('Attack', 'พลังโจมตี', '攻击值'),
        'def' => array('Defense', 'พลังป้องกัน', '生命值'),
        'spd' => array('Speed', 'ความเร็ว', '生命值'),
        'luck' => array('Luck', 'โชค', '生命值'),
        'allStat' => array('All stat', 'ค่าพลังทุกอย่าง', '生命值'),
        'leaderSkill' => array('Leader Skill', 'พลังแม่ทัพ', '生命值'),
        'submit' => array('Submit', 'ยืนยัน', '攻击值'),
        'warriorLimitLv' => array('Character level at least', 'ตัวละครต้องมีเลเว่ลถึง', '攻击值'),
        'limitLv' => array("Limit level", "จำกัดเลเว่ล", "生命值"),
        'enhance' => array('Enhance', 'ตีบวก', '生命值'),
        'fullEnhance' => array('Full Enhance', 'ตีบวกจนเต็ม', '生命值'),
        'have' => array('Have', 'มีอยู่', '攻击值'),
        'sell' => array('Sell', 'ขาย', '攻击值'),
        'fuse' => array('Fuse', 'หลอม', '攻击值'),
        'equip' => array('Equip', 'สวมใส่', '攻击值'),
        'remove' => array('Remove', 'ถอด', '生命值'),
        'removeAll' => array('Remove All', 'ถอดทั้งหมด', '生命值'),
        'autoEquip' => array('Auto Equip', 'สวมอัตโนมัติ', '生命值'),
        'haveAmount' => array('Have Amount', 'มีอยู่จำนวน', '攻击值'),
        'internetProb' => array('Internet Problem', 'ไม่สามารถเชื่อมต่ออินเตอร์เน็ตได้', '生命值'),
        'tryAgain' => array('Try again', 'ลองอีกครั้ง', '生命值'),
        'cancel' => array('Cancel', 'ยกเลิก', '生命值'),
        'dmg' => array('Dmg', 'ความแรง', '生命值'),
        'damage' => array('Damage', 'ความแรง', '生命值'),
        'dmgAcc' => array('Damage Accuracy', 'ความแม่น', '生命值'),
        'cond' => array('Condition', 'สถานะ', '生命值'),
        'chance' => array('Chance', 'โอกาสติด', '生命值'),
        'useChance' => array('Use Chance', 'โอกาสใช้', '生命值'),
        'condAcc' => array('Condition Accuracy', 'ความแม่นของการติดสถานะ', '生命值'),
        //'reactCond' => array('Reaction Condition', 'สถานะสะท้อนกลับ', '生命值'),
        'selfCond' => array('Self Condition', 'ตัวเองติดสถานะ', '生命值'),
        'target' => array('Target', 'เป้าหมาย', '生命值'),
        'active' => array('Active', 'กดใช้', '生命值'),
        'passive' => array('Passive', 'ติดตัว', '生命值'),
        'warriorMustHaveLv' => array('Warrior must have lv', 'ต้องมีเลเว่ลถึง', '生命值'),
        'learn' => array('Learn', 'เรียนรู้', '生命值'),
        'headerWarriorList' => array('Warrior List', 'ตัวละครในคลัง', '生命值'),
        'headerWarriorDetail' => array('Warrior Detail', 'รายละเอียดตัวละคร', '生命值'),
        'headerEquipmentList' => array('Equipment List', 'อุปกรณ์ในคลัง', '生命值'),
        'notEnoughUserLevel' => array('Not enough User level', 'เลเว่ลผู้เล่นไม่เพียงพอ', '生命值'),
        'notEnoughLevel' => array('Not enough level', 'เลเว่ลตัวละครไม่เพียงพอ', '生命值'),
        'notEnoughMoney' => array('Not enough money', 'คุณมีเงินไม่เพียงพอ', '生命值'),
        'notEnoughOre' => array('Not enough ore', 'คุณมีแร่ไม่เพียงพอ', '生命值'),
        'notEnoughHeart' => array('Not enough heart', 'คุณมีหัวใจไม่เพียงพอ', '生命值'),
        'notEnoughDiamond' => array('Not enough diamond', 'คุณมีเพชรไม่เพียงพอ', '生命值'),
        'notEnoughSoul' => array('Not enough soul', 'คุณมีหินวิญญาณไม่เพียงพอ', '生命值'),
        'notEnoughGem' => array('Not enough gem', 'คุณมีอัญมณีไม่เพียงพอ', '生命值'),
        'notEnoughQuestPoint' => array('Not enough quest point', 'คุณมีคะแนนภารกิจไม่เพียงพอ', '生命值'),
        'notHaveWarrior' => array('Not have character for sacrifice', 'คุณไม่มีวัตถุดิบในการบูชายัญ', '生命值'),
        'cannotSacrificeHigherWarrior' => array('Can\'t sacrifice higher character', 'ไม่สามารถบูชายัญตัวละครที่ระดับสูงกว่าได้', '生命值'),
        'cannotFuseLegendaryWeapon' => array('Can\'t fuse legendary weapon', 'ไม่สามารถหลอมอาวุธในตำนานได้', '生命值'),
        'cannotSellLegendaryWeapon' => array('Can\'t sell legendary weapon', 'ไม่สามารถขายอาวุธในตำนานได้', '生命值'),
        'yourBagIsFull' => array('Your bag is full', 'กระเป๋าใส่ของคุณเต็มแล้ว', '生命值'),
        'stockFullDetail' => array('Can\'t remove item, Because your bag is full. Should you upgrade bag or clear item in stock', 'ไม่สามารถถอดของออกได้ เนื่องจากกระเป๋าของคุณเต็ม กรุณาเพิ่มขนาดกระเป๋าหรือทำช่องเก็บของให้ว่างก่อน', '生命值'),
        'stockItem' => array('Stock item', 'คลังไอเท็ม', '生命值'),
        'upgradeBag' => array('Upgrade bag', 'เพิ่มขนาดกระเป๋า', '生命值'),
        'sizeBag' => array('Size bag', 'ขนาดกระเป๋า', '生命值'),
        'increse' => array('Increse', 'เพิ่ม', '生命值'),
        'decrese' => array('Decrese', 'ลด', '生命值'),
        //'dodge' => array('Dodge', 'หลบการโจมตี', '生命值'),
        'blockDmg' => array('Block dmg', 'ป้องกันการโจมตี', '生命值'),
        'forSelf' => array('For self', 'ให้กับตัวเอง', '生命值'),
        'forTeam' => array('For team', 'ให้กับทีม', '生命值'),
        'upgradeHistory' => array('Upgrade History', 'ประวัติการตีบวก', '生命值'),
        'upgradeBySoul' => array('Upgrade By Soul', 'ตีบวกด้วยหินวิญญาณ', '生命值'),
        'upgradeByWarrior' => array('Upgrade By Warrior', 'ตีบวกด้วยนักรบ', '生命值'),
        'increseUseChance' => array('Increse use chance', 'เพิ่มโอกาสใช้', '生命值'),
        'increseAllStatus2x' => array('Increse all stat x2', 'เพิ่มค่าพลังทั้งหมด 2 เท่า', '生命值'),
        'none' => array('None', 'ไม่มี', '生命值'),
        'unlockGemSlot' => array('Unlock gem slot', 'ปลดล็อคช่องใส่เจมตำแหน่งที่', '生命值'),
        'equiped' => array('Equiped', 'สวมใสอยู่', '生命值'),
        'picked' => array('Picked', 'เลือกอยู่', '生命值'),
        'pleaseRemoveEquipedGemFirst' => array('Please remove equiped gem first', 'กรุณาถอดเจมที่สวมอยู่ออกก่อน', '生命值'),
        'normal' => array('Normal', 'ธรรมดา', '生命值'),
        'hard' => array('Hard', 'ยาก', '生命值'),
        'hell' => array('Hell', 'นรก', '生命值'),
        'dropInfo' => array('Drop info', 'ของดรอป', '生命值'),
        'mustPassLevel' => array('You must pass level', 'ต้องผ่านระดับ', '生命值'),
        'first' => array('', 'ก่อน', '生命值'),
        'areaIsLock' => array('You can\'t access this area for now', 'ยังไม่สามารถเข้าไปในพื้นที่นี้ได้', '生命值'),
        'frontRow' => array('Front row', 'แถวหน้า', '生命值'),
        'backRow' => array('Back row', 'แถวหลัง', '生命值'),
        'reserveRow' => array('Reserve row', 'กองหนุน', '生命值'),
        'teamPower' => array('Team power', 'พลังรบ', '生命值'),
        'unlockWhenLv' => array('Unlock when user level', 'ปลดล็อคเมื่อผู้เล่นมีเลเว่ลถึง', '生命值'),
        'store' => array('Store', 'ร้านค้า', '生命值'),
        'unlockWhenVIP' => array('Unlock when user VIP', 'ปลดล็อคเมื่อผู้เล่นมีระดับ VIP', '生命值'),
        'buy' => array('Buy', 'ซื้อ', '生命值'),
        'soul' => array('Soul', 'หินวิญญาณ', '生命值'),
        'confirmRefreshMoneyStore' => array('Confirm refresh store', 'แน่ใจว่าคุณต้องการจะรีเฟลชร้านค้า', '生命值'),
        'completeRefreshMoneyStore' => array('Complete refresh store', 'รีเฟลชร้านค้าเสร็จสิ้น', '生命值'),
        'combineStore' => array('Combine Store', 'ร้านเจียระไนอัญมณี', '生命值'),
        'combine' => array('Combine', 'เจียระไน', '生命值'),
        'get' => array('Get', 'คุณได้รับ', '生命值'),
        'completeUpgradeSkill' => array('Complete upgrade skill', 'อัพเกรดเลเว่ลสกิลเสร็จสิ้น', '生命值'),
        'completeUpgradeWarrior' => array('Complete upgrade warrior', 'อัพเกรดนักรบเสร็จสิ้น', '生命值'),
        'completeLock' => array('Complete lock warrior', 'ล็อคนักรบเสร็จสิ้น', '生命值'),
        'completeUnlock' => array('Complete unlock warrior', 'ปลดล็อคนักรบเสร็จสิ้น', '生命值'),
        'completeEnhance' => array('Complete enhance', 'ตีบวกอุปกรณ์เสร็จสิ้น', '生命值'),
        'completeUnlockGemslot' => array('Complete unlock gem slot', 'ปลดล็อคช่องใส่อัญมณีเสร็จสิ้น', '生命值'),
        'completeUpgradeWarriorBag' => array('Complete upgrade warrior bag', 'อัพเกรดช่องเก็บนักรบเสร็จสิ้น', '生命值'),
        'completeUpgradeEquipmentBag' => array('Complete upgrade equipment bag', 'อัพเกรดช่องเก็บอุปกรณ์เสร็จสิ้น', '生命值'),
        'completeUpgradeGemBag' => array('Complete upgrade bag bag', 'อัพเกรดช่องเก็บอัญมณีเสร็จสิ้น', '生命值'),
        'money' => array('Money', 'เงิน', '生命值'),
        'ore' => array('Ore', 'แร่', '生命值'),
        'inbox' => array('Inbox', 'จดหมาย', '生命值'),
        'view' => array('View', 'ดู', '生命值'),
        'systemSender' => array('System', 'ข้อความระบบ', '生命值'),
        'receipt' => array('Receipt', 'รับ', '生命值'),
        'registerWarrior' => array('Register Warrior', 'รับสมัครนักรบ', '生命值'),
        'oneWarrior' => array('1 Warrior', 'นักรบ 1  คน', '生命值'),
        'oneGreatWarrior' => array('1 Great Warrior', 'นักรบขั้นสูง 1 คน', '生命值'),
        'tenGreatWarrior' => array('10 Great Warrior', 'นักรบขั้นสูง 10 คน', '生命值'),
        'submit' => array('Submit', 'ตกลง', '生命值'),
        'quest' => array('Quest', 'ภารกิจ', '生命值'),
        'dailyquest1' => array('Win Story mode 1 stage', 'ชนะโหมดเนื้อเรื่อง 1 ด่าน', '生命值'),
        'dailyquest2' => array('Upgrade warrior', 'เลื่อนขั้นนักรบ', '生命值'),
        'dailyquest3' => array('Upgrade equipment', 'ตีบวกอุปกรณ์', '生命值'),
        'dailyquest4' => array('Upgrade skill', 'พัฒนาเลเว่ลสกิล', '生命值'),
        'dailyquest5' => array('Fight money dungeon', 'ลงดันเจี้ยนหาเงิน', '生命值'),
        'dailyquest6' => array('Fight ore dungeon', 'ลงดันเจี้ยนหาแร่', '生命值'),
        'dailyquest7' => array('Fight exp dungeon', 'ลงดันเจี้ยนหาประสบการณ์', '生命值'),
        'dailyquest8' => array('Win PVP', 'ชนะการสู้กับผู้เล่นอื่น', '生命值'),
        'dailyquest9' => array('Fight boss', 'สู้กับบอส', '生命值'),
        'dailyquest10' => array('Fight infinity tower', 'ลงหอคอย', '生命值'),
        'go' => array('Go', 'เดินหน้า', '生命值'),
        'time' => array('Time', 'ครั้ง', '生命值'),
        'complete' => array('Complete', 'เสร็จสิ้น', '生命值'),
        'back' => array('Back', 'ย้อนกลับ', '生命值'),
        'warPower' => array('Power', 'พลังรบ', '生命值'),
        'friendList' => array('Friend List', 'รายชื่อเพื่อน', '生命值'),
        'addFriendDone' => array('Add friend done', 'แอดเพื่อนเรียบร้อย', '生命值'),
        'alreadyAdd' => array('You already add this account. Please wait response', 'คุณได้ทำการแอด account นี้ไปแล้ว กรุณารอการตอบรับ', '生命值'),
        'alreadyFriend' => array('You have friend of this account', 'คุณเป็นเพื่อนกับ account นี้อยู่แล้ว', '生命值'),
        'notFoundAccount' => array('Not Found this account', 'ไม่พบ account นี้ในระบบ', '生命值'),
        'pendingYou' => array('This account is pending you accept friend', 'account นี้กำลังรอคุณตอบรับเป็นเพื่อนอยู่', '生命值'),
        'pending' => array('Pending', 'รอรับแอด', '生命值'),
        'accepting' => array('Accepting', 'รอยืนยัน', '生命值'),
        'acceptDone' => array('Accept done', 'ตอบรับเพื่อนเรียบร้อย', '生命值'),
        'cancelFirst' => array('This account is cancel request', 'account นี้ยกเลิกการขอเป็นเพื่อนกับคุณไปแล้ว', '生命值'),
        'cancelDone' => array('Cancel request done', 'ยกเลิกการขอเป็นเพื่อนเรียบร้อย', '生命值'),
        'sendHeartDone' => array('Send heart Done', 'ส่งหัวใจให้เพื่อนเรียบร้อย', '生命值'),
        'alreadySendHeart' => array('Already send heart to all friends', 'คุณได้ส่งหัวใจให้เพื่อนทุกคนแล้ว กรุณาส่งใหม่ในวันพรุ่งนี้ค่ะ', '生命值'),
            /* '' => array('', '', '生命值'),
              '' => array('', '', '生命值'),
              '' => array('', '', '生命值'),
              '' => array('', '', '生命值'),
              '' => array('', '', '生命值'),
              '' => array('', '', '生命值'), */
            //battle scene
    );
    private static $targetArray = array(
        'enemyTarget' => array(
            1 => array('1 unit', 'ศัตรู 1 คน', '生命值'),
            2 => array('horizaltal enemy', 'ศัตรูในแนวนอน', '生命值'),
            3 => array('vertical enemy', 'ศัตรูในแนวตั้ง', '生命值'),
            4 => array('all enemy', 'ศัตรูทั้งหมด', '生命值'),
            5 => array('all character', 'ทุกคนในสนาม', '生命值'),
            6 => array('all character except self', 'ทุกคนในสนามยกเว้นตัวเอง', '生命值'),
        ),
        'selfTarget' => array(
            1 => array('myself', 'ตัวเอง', '生命值'),
            2 => array('all allie', 'ฝ่ายเราทั้งหมด', '生命值'),
        ),
    );

    public static function getWording() {
        return self::$wordingArray;
    }

    public static function getTarget() {
        return self::$targetArray;
    }

}

?>